### ISSUE TITLE
Add response for forge tutorials

### ISSUE THREAD

**Issue by KingRealzYT** [TechnoVisionDev/TechnoBot#27]
Make it so whenever someone asks about the forge tutorials technobot does a response saying they are removed and wont be coming back or something. Looking in chat it seemed very annoying for tails having to do it for 17 different people and it would be better with technobot.

**Comment by TheOnlyTails** [comment]
If you can make a message, I'll fire up a quick PR.

**Comment by xf8b** [comment]
"The Forge tutorials have been discontinued, and no support for Forge will be given."
