### ISSUE TITLE
Extra Withdrawing commands for Technobot

### ISSUE THREAD

**Issue by KingRealzYT** [TechnoVisionDev/TechnoBot#30]
!with, !with all, !with half
This command will make withdrawing money easier as we one won't have to write the full thing (withdraw) and 2 you can just easily withdraw your money depending on if you wanted half of it to come out, if you wanted all of it to come out, or maybe just wanted like 10 or 20 of your moneys to come out.

**Comment by Sparky200** [comment]
Added in PR #33
