### ISSUE TITLE
Suggestions for Technobot Responses

### ISSUE THREAD

**Issue by KingRealzYT** [TechnoVisionDev/TechnoBot#32]
More responses to messages like @TechnoBot
Its very bland and there is only one message, it would be cool if technobot had multiple messages to when you ping him.

**Comment by xf8b** [comment]
who did you just ping on github :concern:

**Comment by KingRealzYT** [comment]
:concern:

**Comment by TechnoVisionDev** [comment]
This suggestion has been added!
