### ISSUE TITLE
Adding onto the !bal command

### ISSUE THREAD

**Issue by KingRealzYT** [TechnoVisionDev/TechnoBot#38]
Make it so we can do !bal (players name) so if you only did !bal then it shows your balance but if you did say (i'll use xf8b) !bal xf8b or !bal mixin (since its his nickname) it will show me his cash, bank, and net worth.

**Comment by TechnoVisionDev** [comment]
We will try to add this in. For some reason we are having strange issues with retrieving members right now

**Comment by TheOnlyTails** [comment]
I'm not sure if you can do that with names. We might only be able to do it with IDs.
