### ISSUE TITLE
Add a pog and pogu reaction

### ISSUE THREAD

**Issue by BHLoneWolf0** [TechnoVisionDev/TechnoBot#40]
when someone sends pog or pogu the bot will send a reaction to pog (if it is written in pog) or pogu (if it is written in pogu)

**Comment by Sparky200** [comment]
This kind of just sounds like extra API requests that'll make the bot ratelimited even more than it already is.

**Comment by TheOnlyTails** [comment]
Isn't it just another event? It doesn't sound that demanding.
