### ISSUE TITLE
@adex720 can you set up a test bot and check if it works?

### ISSUE THREAD

**Issue by adex720** [TechnoVisionDev/TechnoBot#47]
@adex720 can you set up a test bot and check if it works?

_Originally posted by @TheOnlyTails in https://github.com/TechnoVisionDev/TechnoBot/issues/41#issuecomment-755190559_

I have tested the code in my discord bot every time before updating code here. Some imports might still miss. Otherwise it should work

**Comment by TheOnlyTails** [comment]
OK. If the bot works and the game works, it's fine by me.
