### ISSUE TITLE
Members can ping everyone with say command

### ISSUE THREAD

**Issue by zAG6z** [TechnoVisionDev/TechnoBot#49]
**Describe the bug**
Members can ping everyone using the !say command

**How to Replicate**
!say @everyone

**Stacktrace**
n/a

**Comment by xf8b** [comment]
fix immedaitkely !  ! ! :wanr: W:AN! L;WLW:A RnW r: warn !  !  !!

**Comment by KingRealzYT** [comment]
It could be fixed with embeds (just saying)

**Comment by TechnoVisionDev** [comment]
Fixed
