### ISSUE TITLE
Sending !say as an embed

### ISSUE THREAD

**Issue by KingRealzYT** [TechnoVisionDev/TechnoBot#51]
**Is your feature request related to a problem? Please describe.**
People are able to ping others using this and I think people pinged everyone 

**Describe the solution you'd like**
Instead of having !say send as text, it sends as an embed. That way if there is a ping in it the ping won't actually ping anyone.

**Describe alternatives you've considered**
Tbh no alternatives I considered my brains kinda empty

**Additional context**
Nah

**Comment by TechnoVisionDev** [comment]
Added
