### ISSUE TITLE
Untitled Bug

### ISSUE THREAD

**Issue by KingRealzYT** [TechnoVisionDev/TechnoBot#54]
**Describe the bug**
When you do !say you can ping roles by putting the id and then have technobot say it and since he is an admin it will ping them.
Found by PumpkinBear111

**How to Replicate**
!say <@RoleID>

**Stacktrace**

**Comment by KingRealzYT** [comment]
Im just saying a fix to all of this is embeds :O

**Comment by KingRealzYT** [comment]
nevermind someone just tried it and no one got pinged soooo

**Comment by KingRealzYT** [comment]
never mind the never mind someone just pinged everyone level 5 +
again embeds can fix this

**Comment by hirshi001** [comment]
true, but embeds do look weird when using a say command.

**Comment by TheOnlyTails** [comment]
doesn't matter. That's the solution we're going for.

**Comment by KingRealzYT** [comment]
true

**Comment by KingRealzYT** [comment]
but yea as tails said its a solution

**Comment by hirshi001** [comment]
you can check for all the roles and users mentioned in a message.
you can do also check if someone can mention a role by doing role.isMentionable() || member.hasPermission(Permission.MESSAGE_MENTION_EVERYONE)

**Comment by TechnoVisionDev** [comment]
Fixed
