### ISSUE TITLE
New Embed Command?

### ISSUE THREAD

**Issue by KingRealzYT** [TechnoVisionDev/TechnoBot#56]
**Is your feature request related to a problem? Please describe.**
Nah it isn't

**Describe the solution you'd like**
I was thinking an !embed command (with like a 30 minute cooldown or something so it can't be abused) it's like you do !embed and then it asks for the title, the description, and then it asks what channel maybe and you do #(channel). I feel like it would be a cool command to have

**Describe alternatives you've considered**
I dont consider alternatives.

**Additional context**
nah would love to see this tho :O

**Comment by TheOnlyTails** [comment]
Working on it!

**Comment by KingRealzYT** [comment]
I'll just close this issue now
